AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Build S3 bucket for artifacts

Parameters:
  BucketName:
     Type: "String"
     Description: "Name of the S3 bucket"

Resources:
  SamArtifactStorage:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      AccessControl: Private
      VersioningConfiguration:
        Status: Disabled
      LifecycleConfiguration:
        Rules:
          - Id: DeleteDevArtifactsAfterOneDay
            Status: Enabled
            ExpirationInDays: 1
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
