AWSTemplateFormatVersion: '2010-09-09'
Transform: 'AWS::Serverless-2016-10-31'
Description: An AWS Java Events Lambda.
Resources:
  function:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: target/aws-lambda-java-events-demo.jar
      Handler: com.aws.lambda.PersonHandler
      Runtime: java8
      Description: Java Events function
      MemorySize: 512
      Timeout: 10
      # Function's execution role
      Policies:
        - AWSLambdaBasicExecutionRole